from openai import OpenAI
from typing import cast
from openai.types.chat import ChatCompletion

import src.utils.yaml_utils as yaml_utils


# text for LLM prompt - used in generate_packing_list() function
PACKING_PROMPT_TEMPLATE = """
Based on this weather forecast: "{weather_forecast}", generate a specific packing list for a 2-day trip to 
{destination}. Include standard travel essentials (charger, ID) and weather-specific clothing.
Output ONLY a plain, comma-separated list of items. No markdown, no numbers.
Example: Light jacket, Sunglasses, Toothbrush, Phone charger
"""


def ask_gpt(prompt_text: str) -> str:
    """a single isolated function to handle all OpenAI calls"""

    api_key = yaml_utils.get_secret_key()
    openai_client = OpenAI(api_key=api_key)

    # sends a single-turn prompt to OpenAI's model, waiting for a complete, moderately creative text response all at
    # once. a single-turn prompt is a one-time, standalone input given to an AI model that results in a single response,
    # with no ongoing conversation or memory of past chats
    raw_response = openai_client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt_text}],
        temperature=0.5,
        stream=False
    )

    #  tell static type checker to treat the raw_response variable as a ChatCompletion object
    response = cast(ChatCompletion, raw_response)

    # extracts the text answer generated by the AI model from an API response
    content = response.choices[0].message.content

    return content if content is not None else ""


def generate_packing_list(destination: str, weather_forecast: str) -> list[str]:
    """uses the ask_gpt helper to parse the packing list cleanly."""

    print("\nstep 2: generating customized packing list via OpenAI...")

    prompt = PACKING_PROMPT_TEMPLATE.format(
        destination=destination,
        weather_forecast=weather_forecast
    )

    # ask an AI model for a list of things to pack
    raw_list = ask_gpt(prompt).strip()

    return [item.strip() for item in raw_list.split(",") if item.strip()]
