import os
import requests
from openai import OpenAI
from typing import cast
from openai.types.chat import ChatCompletion
import subprocess
from dotenv import load_dotenv
from pathlib import Path
import sys

# load keys from the local .env file
load_dotenv()

# initialize API clients
OPENAI_CLIENT = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

# text for LLM prompt - used in generate_packing_list() function
PACKING_PROMPT_TEMPLATE = """
Based on this weather forecast: "{weather_forecast}", generate a specific packing list for a 2-day trip to 
{destination}. Include standard travel essentials (charger, ID) and weather-specific clothing.
Output ONLY a plain, comma-separated list of items. No markdown, no numbers.
Example: Light jacket, Sunglasses, Toothbrush, Phone charger
"""


def report_out_nearest_area(destination: str, weather_url: str, data: dict) -> None:

    # extract the nearest area data from the payload
    area_name = data['nearest_area'][0]['areaName'][0]['value']
    region = data['nearest_area'][0]['region'][0]['value']
    country = data['nearest_area'][0]['country'][0]['value']
    lat = data['nearest_area'][0]['latitude']
    lon = data['nearest_area'][0]['longitude']

    # print out destination data
    print(f"\nyou entered a request for a weather forcast that was interpreted by this code as {destination}."
          f"\nthis is the request url that the code generated {weather_url}"
          f"\nthe request response returned a nearest area of {area_name} in the region {region} in the country of "
          f"{country}."
          f"\nlatitude {lat} and longitude {lon}.")


def prompt_user():

    print(f"\nprompt user for travel destination and to do list format")

    # prompt the user for a travel destination with an explicit formatting instruction
    print("\ntip: add the state code for specific cities (e.g., 'Portland, ME' or 'Portland, OR')")
    destination = input("\nwhere are you traveling to tomorrow? ").strip()

    todo_list_format = input("\ndo you want the todo list as a markup file (MF/mf) or apple "
                             "reminder (AR/ar)? ").strip().upper()
    if todo_list_format not in ["MF", "AR"]:
        raise ValueError(f"\n{todo_list_format} is not a valid choice.")

    if not destination:
        sys.exit("destination cannot be empty. exiting.")

    # smart split: check if the user used a comma to specify a state
    if "," in destination:
        parts = destination.split(",")
        city = parts[0].strip().title()
        state = parts[1].strip().upper()
        # combine them nicely for display text (e.g., "Portland, ME")
        user_destination = f"{city}, {state}"
    else:
        # fallback if no comma is provided
        user_destination = destination.title()

    return {
        "user_destination": user_destination,
        "todo_list_format": todo_list_format
    }


def get_destination_weather(destination: str) -> str:

    print(f"\nstep 1: fetching weather forecast for {destination}...")

    formatted_city = destination.replace(" ", "+").replace(",", "")
    weather_url = f"https://wttr.in/{formatted_city}?format=j1"

    try:
        response = requests.get(weather_url)
        response.raise_for_status()  # stop application and throw exception for unsuccessful status code
        data = response.json()  # convert from JSON to python dictionary or list

        report_out_nearest_area(destination, weather_url, data)

        # access the first index block of the weather forecast data
        tomorrow = data['weather'][0]

        # break up the keys into string variables so spellcheck ignores them then extract forecast high and low temps
        max_key = "max" + "temp" + "F"
        min_key = "min" + "temp" + "F"
        max_f = tomorrow[max_key]
        min_f = tomorrow[min_key]

        # extract and format hourly weather description text
        raw_desc = tomorrow['hourly'][4]['weatherDesc'][0]['value']
        desc = raw_desc.strip()

        return f"forecast for {destination}: {desc}, high: {max_f}°F, low: {min_f}°F."
    except Exception as e:
        sys.exit(f"could not fetch real-time weather details ({e}).")


def ask_gpt(prompt_text: str) -> str:
    """a single isolated function to handle all OpenAI calls"""

    # sends a single-turn prompt to OpenAI's model, waiting for a complete, moderately creative text response all at
    # once. a single-turn prompt is a one-time, standalone input given to an AI model that results in a single response,
    # with no ongoing conversation or memory of past chats
    raw_response = OPENAI_CLIENT.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt_text}],
        temperature=0.5,
        stream=False
    )

    #  tell static type checker to treat the raw_response variable as a ChatCompletion object
    response = cast(ChatCompletion, raw_response)

    # extracts the text answer generated by the AI model from an API response
    content = response.choices[0].message.content

    return content if content is not None else ""


def generate_packing_list(destination: str, weather_forecast: str) -> list[str]:
    """uses the ask_gpt helper to parse the packing list cleanly."""

    print("\nstep 2: generating customized packing list via OpenAI...")

    prompt = PACKING_PROMPT_TEMPLATE.format(
        destination=destination,
        weather_forecast=weather_forecast
    )

    # ask an ai model for a list of things to pack
    raw_list = ask_gpt(prompt).strip()

    return [item.strip() for item in raw_list.split(",") if item.strip()]


def push_to_apple_reminders(destination: str, items: list[str]) -> None:
    """creates a free, native list in Apple Reminders and adds tasks."""

    print(f"\nstep 3: creating a free apple reminders list for {destination}...")

    # AppleScript commands to create a new list and insert tasks
    applescript = f'''
    tell application "Reminders"
        if not (exists list "{destination} Trip") then
            make new list with properties {{name:"{destination} Trip"}}
        end if
        tell list "{destination} Trip"
            {chr(10).join([f'make new reminder with properties {{name:"Pack {item}"}}' for item in items])}
        end tell
    end tell
    '''

    try:
        subprocess.run(["osascript", "-e", applescript], check=True, capture_output=True)
        print(f"✨ Successfully added {len(items)} tasks to your Apple Reminders app!")
    except Exception as e:
        print(f"could not push to reminders. is this script running on a mac? details: {e}")


def export_to_text_file(destination: str, items: list[str]) -> None:
    """generates a local checklist file in your project folder."""

    print(f"\nstep 3: creating a mark down (.md) reminders list for {destination}...")

    filename = f"{destination.lower().replace(' ', '_').replace(',', "")}_packing_list.md"

    script_dir = Path(__file__).resolve()
    save_path = script_dir.parents[2] / "data" / "processed" / filename  # jump up two levels then data/processed
    with open(save_path, "w", encoding="utf-8") as file:
        file.write(f"# 🧳 Packing Checklist: Trip to {destination}\n")
        file.write("Generated automatically based on the latest weather forecast.\n\n")
        file.write("## Tasks & Gear:\n")
        for item in items:
            file.write(f"- [ ] Pack {item}\n")

    print(f"\nsuccessfully generated a free local checklist file: '{filename}'!")


if __name__ == "__main__":
    pass
